title: Cheng Ouyang, Ph.D.
position: Departmental Lecturer
affiliation: University of Oxford
keywords: Medical Image Computing
google_scholar: https://scholar.google.co.uk/citations?user=Ss_HBpcAAAAJ&hl=en
github_link: https://github.com/cheng-01037
#linkedin: https://www.linkedin.com/
avatar: ./assets/img/avatar.png
#google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
#canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
